--- #YAML:1.0
name:               WWW-LibraryThing
version:            0.0001
abstract:           ~
author:
    - Stefan Hornburg (Racke) <racke@linuxia.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Image::Size:     0
    LWP::UserAgent:  0
    Test::More:      0
    Time::HiRes:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
